import type { PublicProgramResponse, PublicProgramSession } from "../shared/events";
import { useState } from "react";
import { PublicProgramRenderer } from "./PublicProgramRenderer";

const people = ["Maya Chen","Jordan Lee","Leilani Santos","Amina Patel","Miguel Alvarez","Nina Williams","Priya Natarajan","Jason Kai","Sofia Tran","Arjun Dey","Meredith Wilson","Devon Hughes","Leena Park","Ravi Kumar","Hannah Kim","Taylor Kim"];
const speakers = people.map((name, index) => ({ id:`person-${index}`,name,biography:"",title:"",company:"",headshotAssetId:null,sessionIds:[] }));
const roomNames: Record<string,string> = { harbor:"Harbor Hall", atlas:"Atlas Room", studio:"Studio B", beacon:"Beacon Room" };
function session(id:string,title:string,start:string,minutes:number,roomId:string,trackId:string,trackName:string,speakerIndex?:number,format="Talk"):PublicProgramSession {
  const startsAt=`2026-10-07T${start}:00.000Z`; const person=speakerIndex === undefined ? undefined : speakers[speakerIndex];
  return {id,title,description:`${title} at Pacific Open Data Summit.`,format,trackId,trackName,roomId,roomName:roomNames[roomId],roomPending:false,startsAt,endsAt:new Date(new Date(startsAt).getTime()+minutes*60000).toISOString(),day:"2026-10-07",calendarUid:`fixture-${id}`,calendarSequence:0,speakers:person?[{id:person.id,name:person.name,title:"",company:"",role:"primary"}]:[]};
}
const tracks=[{id:"keynote",name:"Keynote"},{id:"governance",name:"Governance"},{id:"capacity",name:"Capacity Building"},{id:"technology",name:"Technology"},{id:"applications",name:"Applications"},{id:"community",name:"Community"}];
const data:PublicProgramResponse={event:{id:"itinerary-fixture",name:"Pacific Open Data Summit 2026",startsOn:"2026-10-07",endsOn:"2026-10-08",timezone:"UTC",themeAccent:"#2f5d98",tracks,rooms:Object.entries(roomNames).map(([id,name])=>({id,name,readiness:"ready" as const}))},revision:{id:"fixture-revision",version:4,publishedAt:"2026-08-14T12:00:00Z",isCurrent:true},revisions:[{id:"fixture-revision",version:4,publishedAt:"2026-08-14T12:00:00Z",isCurrent:true}],speakers,sessions:[
  session("registration","Registration & Breakfast","08:00",60,"harbor","","",undefined,"Break"),
  session("keynote","Public Infrastructure for Everyone","09:00",60,"harbor","keynote","Keynote",0,"Keynote"),
  session("trust","Designing Trustworthy Data Systems","10:15",60,"harbor","governance","Governance",1,"Panel"),session("ai-good","AI for Public Good: Real-World Use Cases","10:15",45,"atlas","technology","Technology",1),session("climate","Mapping Climate Risk with Open Data","10:15",45,"studio","applications","Applications",2),session("stories","Community Data Stories That Drive Change","10:15",60,"beacon","community","Community",3),
  session("standards","Open Data Standards That Scale","11:15",45,"atlas","technology","Technology",4),session("impact","Measuring Impact with Open Data","11:15",45,"studio","applications","Applications",5),session("value","From Open Data to Public Value","11:30",90,"harbor","capacity","Capacity Building",6,"Workshop"),session("privacy","Privacy, Ethics & Data Stewardship","11:30",60,"beacon","governance","Governance",11),
  session("lunch","Lunch","12:30",60,"atlas","","",undefined,"Break"),
  session("cities","Open Data for Smarter Cities","13:30",45,"harbor","applications","Applications",7),session("literacy","Building Data Literacy in Communities","13:30",45,"atlas","capacity","Capacity Building",8),session("pipelines","Data Pipelines That Last","13:30",45,"studio","technology","Technology",9),session("sovereignty","Indigenous Data Sovereignty","13:30",45,"beacon","community","Community",10),
  session("policy","Policy Levers for Open Data","14:30",60,"harbor","governance","Governance",12),session("health","Open Data in Public Health","14:30",45,"atlas","applications","Applications",13),session("projects","Facilitating Data Projects That Stick","14:30",60,"studio","capacity","Capacity Building",14),session("apis","APIs for Open Data","14:30",45,"beacon","technology","Technology",15),
  session("outcomes","Partnering for Stronger Outcomes","15:30",60,"harbor","community","Community",2),session("budgeting","Open Budgeting for Transparency","15:30",45,"atlas","governance","Governance",13),session("visualizing","Visualizing Data That Matters","15:30",45,"studio","applications","Applications",14),session("practice","From Insight to Action: Data in Practice","15:30",60,"beacon","capacity","Capacity Building",6),session("closing","Closing Remarks","16:45",30,"harbor","","",undefined,"Closing"),
  {...session("day-two","Open Data Futures","09:00",60,"harbor","keynote","Keynote",0,"Keynote"),day:"2026-10-08",startsAt:null,endsAt:null}
]};
export function ItineraryEmbedFixture(){const [selected,setSelected]=useState<string|null>("trust");return <main className="program-shell mode-embed"><PublicProgramRenderer data={data} mode="embed" widget="itinerary" selectedSessionId={selected} initialItinerarySessionIds={["keynote","trust","value"]} onSelectSession={setSelected} /></main>}
